spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: imagecore-backend-user-service
          uri: lb://imagecore-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: imagecore-backend-picture-service
          uri: lb://imagecore-backend-picture-service
          predicates:
            - Path=/api/picture/**
        - id: imagecore-backend-space-service
          uri: lb://imagecore-backend-space-service
          predicates:
            - Path=/api/space/**
  application:
    name: imagecore-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8110

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

