server:
  port: 8103
  servlet:
    context-path: /api/picture
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: imagecore-backend-picture-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx
    username: root
    password: 123456
  # Redis 配置
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.tech.imagecorebackendpictureservice.interfaces.controller

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer
  consumer:
    group: canalGroup

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
imagocore:
  caffeine:
    initial-capacity: 1024
    maximum-size: 10000
    expire-time: 5
## 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: xxx
#    secretId: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx

## 阿里云 AI 配置
#aliYunAi:
#  apiKey: xxx
